// Code generated by goyacc -o parser.go parser.go.y. DO NOT EDIT.

//line parser.go.y:2
package internal

import __yyfmt__ "fmt"

//line parser.go.y:2

//line parser.go.y:6
type yySymType struct {
	yys      int
	token    Token
	expr     interface{}
	exprList []interface{}
	exprMap  map[string]interface{}
}

const LITERAL_NIL = 57346
const LITERAL_BOOL = 57347
const LITERAL_NUMBER = 57348
const LITERAL_STRING = 57349
const IDENT = 57350
const AND = 57351
const OR = 57352
const EQL = 57353
const NEQ = 57354
const LSS = 57355
const GTR = 57356
const LEQ = 57357
const GEQ = 57358
const SHL = 57359
const SHR = 57360
const BIT_NOT = 57361
const IN = 57362

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LITERAL_NIL",
	"LITERAL_BOOL",
	"LITERAL_NUMBER",
	"LITERAL_STRING",
	"IDENT",
	"AND",
	"OR",
	"EQL",
	"NEQ",
	"LSS",
	"GTR",
	"LEQ",
	"GEQ",
	"SHL",
	"SHR",
	"BIT_NOT",
	"IN",
	"'?'",
	"':'",
	"'|'",
	"'^'",
	"'&'",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"'!'",
	"'.'",
	"'['",
	"']'",
	"'('",
	"')'",
	"'{'",
	"'}'",
	"','",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.go.y:146

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 597

var yyAct = [...]int8{
	45, 2, 90, 81, 82, 80, 42, 79, 72, 41,
	47, 44, 80, 38, 39, 7, 48, 49, 50, 51,
	52, 53, 54, 55, 57, 58, 59, 60, 61, 62,
	63, 64, 65, 66, 67, 68, 69, 70, 71, 6,
	73, 75, 5, 4, 31, 32, 25, 26, 27, 28,
	29, 30, 36, 37, 78, 40, 19, 85, 33, 35,
	34, 20, 21, 22, 23, 24, 40, 38, 39, 3,
	1, 76, 0, 0, 0, 88, 0, 0, 38, 39,
	0, 91, 0, 92, 93, 94, 0, 0, 95, 31,
	32, 25, 26, 27, 28, 29, 30, 36, 37, 100,
	40, 19, 87, 33, 35, 34, 20, 21, 22, 23,
	24, 0, 38, 39, 86, 31, 32, 25, 26, 27,
	28, 29, 30, 36, 37, 0, 40, 19, 0, 33,
	35, 34, 20, 21, 22, 23, 24, 0, 38, 39,
	99, 31, 32, 25, 26, 27, 28, 29, 30, 36,
	37, 0, 40, 19, 0, 33, 35, 34, 20, 21,
	22, 23, 24, 0, 38, 39, 97, 31, 32, 25,
	26, 27, 28, 29, 30, 36, 37, 0, 40, 19,
	98, 33, 35, 34, 20, 21, 22, 23, 24, 0,
	38, 39, 31, 32, 25, 26, 27, 28, 29, 30,
	36, 37, 0, 40, 19, 84, 33, 35, 34, 20,
	21, 22, 23, 24, 0, 38, 39, 31, 32, 25,
	26, 27, 28, 29, 30, 36, 37, 0, 40, 19,
	83, 33, 35, 34, 20, 21, 22, 23, 24, 0,
	38, 39, 31, 32, 25, 26, 27, 28, 29, 30,
	36, 37, 0, 40, 19, 0, 33, 35, 34, 20,
	21, 22, 23, 24, 0, 38, 39, 31, 0, 25,
	26, 27, 28, 29, 30, 36, 37, 0, 40, 0,
	0, 33, 35, 34, 20, 21, 22, 23, 24, 0,
	38, 39, 25, 26, 27, 28, 29, 30, 36, 37,
	0, 40, 0, 0, 33, 35, 34, 20, 21, 22,
	23, 24, 0, 38, 39, 25, 26, 27, 28, 29,
	30, 36, 37, 0, 40, 0, 0, 0, 35, 34,
	20, 21, 22, 23, 24, 0, 38, 39, 25, 26,
	27, 28, 29, 30, 36, 37, 0, 40, 0, 0,
	0, 0, 34, 20, 21, 22, 23, 24, 0, 38,
	39, 10, 11, 12, 13, 9, 0, 0, 0, 40,
	10, 11, 12, 13, 9, 0, 18, 22, 23, 24,
	0, 38, 39, 0, 16, 18, 0, 0, 17, 0,
	14, 0, 8, 16, 15, 46, 0, 17, 0, 14,
	96, 8, 0, 15, 10, 11, 12, 13, 9, 27,
	28, 29, 30, 36, 37, 0, 40, 0, 0, 18,
	0, 0, 20, 21, 22, 23, 24, 16, 38, 39,
	0, 17, 0, 14, 89, 8, 0, 15, 25, 26,
	27, 28, 29, 30, 36, 37, 0, 40, 10, 11,
	12, 13, 9, 20, 21, 22, 23, 24, 0, 38,
	39, 0, 0, 18, 0, 0, 0, 0, 0, 0,
	0, 16, 0, 0, 0, 17, 0, 14, 0, 8,
	77, 15, 10, 11, 12, 13, 9, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 18, 0, 0,
	74, 0, 0, 0, 0, 16, 0, 0, 0, 17,
	0, 14, 0, 8, 0, 15, 10, 11, 12, 13,
	9, 10, 11, 12, 13, 9, 0, 0, 0, 0,
	0, 18, 0, 0, 0, 0, 18, 0, 0, 16,
	56, 0, 0, 17, 16, 14, 0, 8, 17, 15,
	14, 43, 8, 0, 15, 10, 11, 12, 13, 9,
	0, 0, 0, 0, 36, 37, 0, 40, 0, 0,
	18, 0, 0, 20, 21, 22, 23, 24, 16, 38,
	39, 0, 17, 40, 14, 0, 8, 0, 15, 20,
	21, 22, 23, 24, 0, 38, 39,
}

var yyPact = [...]int16{
	551, -1000, 233, -1000, -1000, -1000, -1000, -1000, 551, -29,
	-1000, -1000, -1000, -1000, 517, 357, 551, 551, 551, 551,
	551, 551, 512, 551, 551, 551, 551, 551, 551, 551,
	551, 551, 551, 551, 551, 551, 551, 551, 0, 478,
	551, 35, 444, -1000, -27, 233, -1000, -35, 208, 46,
	46, 46, 183, 349, 349, 46, 551, 46, 46, 396,
	396, 547, 547, 547, 547, 281, 258, 304, 427, 327,
	563, 563, -1000, 80, 400, -19, -1000, -1000, -34, -1000,
	551, -1000, 551, 551, 551, 46, -1000, 366, 132, -1000,
	-1000, 233, 158, 233, 233, 106, -1000, -1000, 551, -1000,
	233,
}

var yyPgo = [...]int8{
	0, 70, 0, 69, 43, 42, 39, 15, 11, 10,
}

var yyR1 = [...]int8{
	0, 1, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 3, 3, 3, 3, 3, 3, 3, 3, 4,
	4, 4, 4, 4, 4, 4, 5, 5, 5, 5,
	5, 5, 5, 5, 5, 6, 6, 6, 6, 6,
	6, 7, 7, 7, 7, 7, 7, 7, 7, 8,
	8, 9, 9,
}

var yyR2 = [...]int8{
	0, 1, 1, 1, 1, 1, 1, 5, 3, 3,
	4, 1, 1, 1, 1, 2, 3, 2, 3, 2,
	3, 3, 3, 3, 4, 3, 2, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	2, 1, 3, 4, 3, 6, 5, 5, 4, 1,
	3, 3, 5,
}

var yyChk = [...]int16{
	-1000, -1, -2, -3, -4, -5, -6, -7, 35, 8,
	4, 5, 6, 7, 33, 37, 27, 31, 19, 21,
	26, 27, 28, 29, 30, 11, 12, 13, 14, 15,
	16, 9, 10, 23, 25, 24, 17, 18, 32, 33,
	20, -2, 35, 34, -8, -2, 38, -9, -2, -2,
	-2, -2, -2, -2, -2, -2, 28, -2, -2, -2,
	-2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
	-2, -2, 8, -2, 22, -2, 36, 36, -8, 34,
	39, 38, 39, 22, 22, -2, 34, 22, -2, 34,
	36, -2, -2, -2, -2, -2, 34, 34, 22, 34,
	-2,
}

var yyDef = [...]int8{
	0, -2, 1, 2, 3, 4, 5, 6, 0, 41,
	11, 12, 13, 14, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 15, 0, 49, 17, 0, 0, 19,
	26, 40, 0, 20, 21, 22, 0, 23, 25, 27,
	28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
	38, 39, 42, 0, 0, 44, 8, 9, 0, 16,
	0, 18, 0, 0, 0, 24, 43, 0, 0, 48,
	10, 50, 0, 51, 7, 0, 47, 46, 0, 45,
	52,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 31, 3, 3, 3, 30, 25, 3,
	35, 36, 28, 26, 39, 27, 32, 29, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 22, 3,
	3, 3, 3, 21, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 33, 3, 34, 24, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 37, 23, 38,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:65
		{
			yyVAL.expr = yyDollar[1].expr
			yylex.(*Lexer).result = yyVAL.expr
		}
	case 7:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:77
		{
			if asBool(yyDollar[1].expr) {
				yyVAL.expr = yyDollar[3].expr
			} else {
				yyVAL.expr = yyDollar[5].expr
			}
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:78
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:79
		{
			yyVAL.expr = callFunction(yylex.(*Lexer).functions, yyDollar[1].token.literal, []interface{}{})
		}
	case 10:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:80
		{
			yyVAL.expr = callFunction(yylex.(*Lexer).functions, yyDollar[1].token.literal, yyDollar[3].exprList)
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:84
		{
			yyVAL.expr = nil
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:85
		{
			yyVAL.expr = yyDollar[1].token.value
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:86
		{
			yyVAL.expr = yyDollar[1].token.value
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:87
		{
			yyVAL.expr = yyDollar[1].token.value
		}
	case 15:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:88
		{
			yyVAL.expr = []interface{}{}
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:89
		{
			yyVAL.expr = yyDollar[2].exprList
		}
	case 17:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:90
		{
			yyVAL.expr = map[string]interface{}{}
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:91
		{
			yyVAL.expr = yyDollar[2].exprMap
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:95
		{
			yyVAL.expr = unaryMinus(yyDollar[2].expr)
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:96
		{
			yyVAL.expr = add(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:97
		{
			yyVAL.expr = sub(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:98
		{
			yyVAL.expr = mul(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:99
		{
			yyVAL.expr = div(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 24:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:100
		{
			yyVAL.expr = pow(yyDollar[1].expr, yyDollar[4].expr)
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:101
		{
			yyVAL.expr = mod(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 26:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:105
		{
			yyVAL.expr = !asBool(yyDollar[2].expr)
		}
	case 27:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:106
		{
			yyVAL.expr = deepEqual(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:107
		{
			yyVAL.expr = !deepEqual(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:108
		{
			yyVAL.expr = compare(yyDollar[1].expr, yyDollar[3].expr, "<")
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:109
		{
			yyVAL.expr = compare(yyDollar[1].expr, yyDollar[3].expr, ">")
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:110
		{
			yyVAL.expr = compare(yyDollar[1].expr, yyDollar[3].expr, "<=")
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:111
		{
			yyVAL.expr = compare(yyDollar[1].expr, yyDollar[3].expr, ">=")
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:112
		{
			left := asBool(yyDollar[1].expr)
			right := asBool(yyDollar[3].expr)
			yyVAL.expr = left && right
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:113
		{
			left := asBool(yyDollar[1].expr)
			right := asBool(yyDollar[3].expr)
			yyVAL.expr = left || right
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:117
		{
			yyVAL.expr = asInteger(yyDollar[1].expr) | asInteger(yyDollar[3].expr)
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:118
		{
			yyVAL.expr = asInteger(yyDollar[1].expr) & asInteger(yyDollar[3].expr)
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:119
		{
			yyVAL.expr = asInteger(yyDollar[1].expr) ^ asInteger(yyDollar[3].expr)
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:120
		{
			l := asInteger(yyDollar[1].expr)
			r := asInteger(yyDollar[3].expr)
			if r >= 0 {
				yyVAL.expr = l << uint(r)
			} else {
				yyVAL.expr = l >> uint(-r)
			}
		}
	case 39:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:121
		{
			l := asInteger(yyDollar[1].expr)
			r := asInteger(yyDollar[3].expr)
			if r >= 0 {
				yyVAL.expr = l >> uint(r)
			} else {
				yyVAL.expr = l << uint(-r)
			}
		}
	case 40:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:122
		{
			yyVAL.expr = ^asInteger(yyDollar[2].expr)
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:126
		{
			yyVAL.expr = accessVar(yylex.(*Lexer).variables, yyDollar[1].token.literal)
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:127
		{
			yyVAL.expr = accessField(yyDollar[1].expr, yyDollar[3].token.literal)
		}
	case 43:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:128
		{
			yyVAL.expr = accessField(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:129
		{
			yyVAL.expr = arrayContains(yyDollar[3].expr, yyDollar[1].expr)
		}
	case 45:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:130
		{
			yyVAL.expr = slice(yyDollar[1].expr, yyDollar[3].expr, yyDollar[5].expr)
		}
	case 46:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:131
		{
			yyVAL.expr = slice(yyDollar[1].expr, nil, yyDollar[4].expr)
		}
	case 47:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:132
		{
			yyVAL.expr = slice(yyDollar[1].expr, yyDollar[3].expr, nil)
		}
	case 48:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:133
		{
			yyVAL.expr = slice(yyDollar[1].expr, nil, nil)
		}
	case 49:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:137
		{
			yyVAL.exprList = []interface{}{yyDollar[1].expr}
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:138
		{
			yyVAL.exprList = append(yyDollar[1].exprList, yyDollar[3].expr)
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:142
		{
			yyVAL.exprMap = make(map[string]interface{})
			yyVAL.exprMap[asObjectKey(yyDollar[1].expr)] = yyDollar[3].expr
		}
	case 52:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:143
		{
			yyVAL.exprMap = addObjectMember(yyDollar[1].exprMap, yyDollar[3].expr, yyDollar[5].expr)
		}
	}
	goto yystack /* stack new state and value */
}
