// Code generated by goyacc -o parser.go parser.go.y. DO NOT EDIT.

//line parser.go.y:2
package internal

import __yyfmt__ "fmt"

//line parser.go.y:2

//line parser.go.y:6
type yySymType struct {
	yys      int
	token    Token
	expr     interface{}
	exprList []interface{}
	exprMap  map[string]interface{}
}

const LITERAL_NIL = 57346
const LITERAL_BOOL = 57347
const LITERAL_NUMBER = 57348
const LITERAL_STRING = 57349
const IDENT = 57350
const AND = 57351
const OR = 57352
const EQL = 57353
const NEQ = 57354
const LSS = 57355
const GTR = 57356
const LEQ = 57357
const GEQ = 57358
const SHL = 57359
const SHR = 57360
const BIT_NOT = 57361
const IN = 57362

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LITERAL_NIL",
	"LITERAL_BOOL",
	"LITERAL_NUMBER",
	"LITERAL_STRING",
	"IDENT",
	"AND",
	"OR",
	"EQL",
	"NEQ",
	"LSS",
	"GTR",
	"LEQ",
	"GEQ",
	"SHL",
	"SHR",
	"BIT_NOT",
	"IN",
	"'|'",
	"'^'",
	"'&'",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"'!'",
	"'.'",
	"'['",
	"']'",
	"'?'",
	"':'",
	"'('",
	"')'",
	"'{'",
	"'}'",
	"','",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.go.y:146

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 579

var yyAct = [...]int{
	45, 2, 88, 80, 81, 79, 78, 38, 39, 41,
	19, 42, 19, 79, 71, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 7,
	72, 74, 31, 32, 25, 26, 27, 28, 29, 30,
	36, 37, 6, 40, 33, 35, 34, 20, 21, 22,
	23, 24, 5, 38, 39, 40, 19, 4, 3, 75,
	1, 22, 23, 24, 86, 38, 39, 0, 19, 0,
	89, 0, 90, 91, 92, 0, 93, 31, 32, 25,
	26, 27, 28, 29, 30, 36, 37, 98, 40, 33,
	35, 34, 20, 21, 22, 23, 24, 0, 38, 39,
	84, 19, 85, 31, 32, 25, 26, 27, 28, 29,
	30, 36, 37, 0, 40, 33, 35, 34, 20, 21,
	22, 23, 24, 0, 38, 39, 0, 19, 96, 31,
	32, 25, 26, 27, 28, 29, 30, 36, 37, 0,
	40, 33, 35, 34, 20, 21, 22, 23, 24, 0,
	38, 39, 0, 19, 83, 31, 32, 25, 26, 27,
	28, 29, 30, 36, 37, 0, 40, 33, 35, 34,
	20, 21, 22, 23, 24, 0, 38, 39, 0, 19,
	82, 31, 32, 25, 26, 27, 28, 29, 30, 36,
	37, 0, 40, 33, 35, 34, 20, 21, 22, 23,
	24, 0, 38, 39, 97, 19, 31, 32, 25, 26,
	27, 28, 29, 30, 36, 37, 0, 40, 33, 35,
	34, 20, 21, 22, 23, 24, 0, 38, 39, 95,
	19, 31, 32, 25, 26, 27, 28, 29, 30, 36,
	37, 0, 40, 33, 35, 34, 20, 21, 22, 23,
	24, 0, 38, 39, 31, 19, 25, 26, 27, 28,
	29, 30, 36, 37, 0, 40, 33, 35, 34, 20,
	21, 22, 23, 24, 0, 38, 39, 44, 19, 25,
	26, 27, 28, 29, 30, 36, 37, 0, 40, 33,
	35, 34, 20, 21, 22, 23, 24, 0, 38, 39,
	0, 19, 25, 26, 27, 28, 29, 30, 36, 37,
	0, 40, 0, 35, 34, 20, 21, 22, 23, 24,
	77, 38, 39, 0, 19, 25, 26, 27, 28, 29,
	30, 36, 37, 0, 40, 0, 0, 34, 20, 21,
	22, 23, 24, 0, 38, 39, 0, 19, 25, 26,
	27, 28, 29, 30, 36, 37, 0, 40, 0, 0,
	0, 20, 21, 22, 23, 24, 0, 38, 39, 0,
	19, 10, 11, 12, 13, 9, 0, 40, 0, 0,
	0, 20, 21, 22, 23, 24, 18, 38, 39, 0,
	19, 0, 16, 0, 0, 0, 17, 0, 14, 0,
	0, 40, 8, 0, 15, 46, 10, 11, 12, 13,
	9, 38, 39, 0, 19, 10, 11, 12, 13, 9,
	0, 18, 0, 0, 0, 0, 0, 16, 0, 0,
	18, 17, 0, 14, 94, 0, 16, 8, 0, 15,
	17, 0, 14, 87, 0, 0, 8, 0, 15, 10,
	11, 12, 13, 9, 0, 0, 0, 0, 10, 11,
	12, 13, 9, 0, 18, 0, 0, 0, 0, 0,
	16, 0, 0, 18, 17, 0, 14, 0, 0, 16,
	8, 76, 15, 17, 0, 14, 0, 0, 73, 8,
	0, 15, 10, 11, 12, 13, 9, 10, 11, 12,
	13, 9, 0, 0, 0, 0, 0, 18, 0, 0,
	0, 0, 18, 16, 0, 0, 0, 17, 16, 14,
	43, 0, 17, 8, 14, 15, 0, 0, 8, 0,
	15, 27, 28, 29, 30, 36, 37, 0, 40, 0,
	0, 0, 20, 21, 22, 23, 24, 0, 38, 39,
	0, 19, 36, 37, 0, 40, 0, 0, 0, 20,
	21, 22, 23, 24, 0, 38, 39, 0, 19,
}

var yyPact = [...]int{
	503, -1000, 232, -1000, -1000, -1000, -1000, -1000, 503, -24,
	-1000, -1000, -1000, -1000, 498, 377, 503, 503, 503, 503,
	503, 503, 503, 503, 503, 503, 503, 503, 503, 503,
	503, 503, 503, 503, 503, 503, 503, 503, 6, 464,
	503, 33, 455, -1000, -26, 232, -1000, -35, 156, 391,
	391, 391, 130, 45, 45, 391, 391, 391, 528, 528,
	545, 545, 545, 545, 278, 255, 301, 347, 324, 367,
	367, -1000, 78, 421, -23, -1000, -1000, -34, -1000, 503,
	-1000, 503, 503, 503, -1000, 412, 207, -1000, -1000, 232,
	104, 232, -21, 182, -1000, -1000, 503, -1000, 232,
}

var yyPgo = [...]int{
	0, 70, 0, 68, 67, 62, 52, 39, 287, 15,
}

var yyR1 = [...]int{
	0, 1, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 3, 3, 3, 3, 3, 3, 3, 3, 4,
	4, 4, 4, 4, 4, 5, 5, 5, 5, 5,
	5, 5, 5, 5, 6, 6, 6, 6, 6, 6,
	7, 7, 7, 7, 7, 7, 7, 7, 8, 8,
	9, 9,
}

var yyR2 = [...]int{
	0, 1, 1, 1, 1, 1, 1, 5, 3, 3,
	4, 1, 1, 1, 1, 2, 3, 2, 3, 2,
	3, 3, 3, 3, 3, 2, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 2,
	1, 3, 4, 3, 6, 5, 5, 4, 1, 3,
	3, 5,
}

var yyChk = [...]int{
	-1000, -1, -2, -3, -4, -5, -6, -7, 35, 8,
	4, 5, 6, 7, 31, 37, 25, 29, 19, 33,
	24, 25, 26, 27, 28, 11, 12, 13, 14, 15,
	16, 9, 10, 21, 23, 22, 17, 18, 30, 31,
	20, -2, 35, 32, -8, -2, 38, -9, -2, -2,
	-2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
	-2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
	-2, 8, -2, 34, -2, 36, 36, -8, 32, 39,
	38, 39, 34, 34, 32, 34, -2, 32, 36, -2,
	-2, -2, -2, -2, 32, 32, 34, 32, -2,
}

var yyDef = [...]int{
	0, -2, 1, 2, 3, 4, 5, 6, 0, 40,
	11, 12, 13, 14, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 15, 0, 48, 17, 0, 0, 19,
	25, 39, 0, 20, 21, 22, 23, 24, 26, 27,
	28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
	38, 41, 0, 0, 43, 8, 9, 0, 16, 0,
	18, 0, 0, 0, 42, 0, 0, 47, 10, 49,
	0, 50, 7, 0, 46, 45, 0, 44, 51,
}

var yyTok1 = [...]int{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 29, 3, 3, 3, 28, 23, 3,
	35, 36, 26, 24, 39, 25, 30, 27, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 34, 3,
	3, 3, 3, 33, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 31, 3, 32, 22, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 37, 21, 38,
}

var yyTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20,
}

var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:65
		{
			yyVAL.expr = yyDollar[1].expr
			yylex.(*Lexer).result = yyVAL.expr
		}
	case 7:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:77
		{
			l := yyDollar[1].expr
			if asBool(l) {
				yyVAL.expr = yyDollar[3].expr
			} else {
				yyVAL.expr = yyDollar[5].expr
			}
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:78
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:79
		{
			yyVAL.expr = callFunction(yylex.(*Lexer).functions, yyDollar[1].token.literal, []interface{}{})
		}
	case 10:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:80
		{
			yyVAL.expr = callFunction(yylex.(*Lexer).functions, yyDollar[1].token.literal, yyDollar[3].exprList)
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:85
		{
			yyVAL.expr = nil
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:86
		{
			yyVAL.expr = yyDollar[1].token.value
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:87
		{
			yyVAL.expr = yyDollar[1].token.value
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:88
		{
			yyVAL.expr = yyDollar[1].token.value
		}
	case 15:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:89
		{
			yyVAL.expr = []interface{}{}
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:90
		{
			yyVAL.expr = yyDollar[2].exprList
		}
	case 17:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:91
		{
			yyVAL.expr = map[string]interface{}{}
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:92
		{
			yyVAL.expr = yyDollar[2].exprMap
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:96
		{
			yyVAL.expr = unaryMinus(yyDollar[2].expr)
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:97
		{
			yyVAL.expr = add(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:98
		{
			yyVAL.expr = sub(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:99
		{
			yyVAL.expr = mul(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:100
		{
			yyVAL.expr = div(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:101
		{
			yyVAL.expr = mod(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 25:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:105
		{
			yyVAL.expr = !asBool(yyDollar[2].expr)
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:106
		{
			yyVAL.expr = deepEqual(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 27:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:107
		{
			yyVAL.expr = !deepEqual(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:108
		{
			yyVAL.expr = compare(yyDollar[1].expr, yyDollar[3].expr, "<")
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:109
		{
			yyVAL.expr = compare(yyDollar[1].expr, yyDollar[3].expr, ">")
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:110
		{
			yyVAL.expr = compare(yyDollar[1].expr, yyDollar[3].expr, "<=")
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:111
		{
			yyVAL.expr = compare(yyDollar[1].expr, yyDollar[3].expr, ">=")
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:112
		{
			left := asBool(yyDollar[1].expr)
			right := asBool(yyDollar[3].expr)
			yyVAL.expr = left && right
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:113
		{
			left := asBool(yyDollar[1].expr)
			right := asBool(yyDollar[3].expr)
			yyVAL.expr = left || right
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:117
		{
			yyVAL.expr = asInteger(yyDollar[1].expr) | asInteger(yyDollar[3].expr)
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:118
		{
			yyVAL.expr = asInteger(yyDollar[1].expr) & asInteger(yyDollar[3].expr)
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:119
		{
			yyVAL.expr = asInteger(yyDollar[1].expr) ^ asInteger(yyDollar[3].expr)
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:120
		{
			l := asInteger(yyDollar[1].expr)
			r := asInteger(yyDollar[3].expr)
			if r >= 0 {
				yyVAL.expr = l << uint(r)
			} else {
				yyVAL.expr = l >> uint(-r)
			}
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:121
		{
			l := asInteger(yyDollar[1].expr)
			r := asInteger(yyDollar[3].expr)
			if r >= 0 {
				yyVAL.expr = l >> uint(r)
			} else {
				yyVAL.expr = l << uint(-r)
			}
		}
	case 39:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:122
		{
			yyVAL.expr = ^asInteger(yyDollar[2].expr)
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:126
		{
			yyVAL.expr = accessVar(yylex.(*Lexer).variables, yyDollar[1].token.literal)
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:127
		{
			yyVAL.expr = accessField(yyDollar[1].expr, yyDollar[3].token.literal)
		}
	case 42:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:128
		{
			yyVAL.expr = accessField(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:129
		{
			yyVAL.expr = arrayContains(yyDollar[3].expr, yyDollar[1].expr)
		}
	case 44:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:130
		{
			yyVAL.expr = slice(yyDollar[1].expr, yyDollar[3].expr, yyDollar[5].expr)
		}
	case 45:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:131
		{
			yyVAL.expr = slice(yyDollar[1].expr, nil, yyDollar[4].expr)
		}
	case 46:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:132
		{
			yyVAL.expr = slice(yyDollar[1].expr, yyDollar[3].expr, nil)
		}
	case 47:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:133
		{
			yyVAL.expr = slice(yyDollar[1].expr, nil, nil)
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:137
		{
			yyVAL.exprList = []interface{}{yyDollar[1].expr}
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:138
		{
			yyVAL.exprList = append(yyDollar[1].exprList, yyDollar[3].expr)
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:142
		{
			yyVAL.exprMap = make(map[string]interface{})
			yyVAL.exprMap[asObjectKey(yyDollar[1].expr)] = yyDollar[3].expr
		}
	case 51:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:143
		{
			yyVAL.exprMap = addObjectMember(yyDollar[1].exprMap, yyDollar[3].expr, yyDollar[5].expr)
		}
	}
	goto yystack /* stack new state and value */
}
